project:
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js

website:  
  title: "r-shinylive in Quarto"
 
format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true